### ISSUE TITLE
Filtrování glyfů ve výsledných souborech

### ISSUE THREAD

**Issue by pepe** [LastStar/letra#1]
při volání metody load, je možné přidat option[:glyph_indices] se souborem s glyfy, které se mají objevit ve výsledných webfontech.

**Comment by simi** [comment]
Tak @pepe, přidal jsem tedy i další možnosti.

``` ruby
letra = Letra.load(:source_file => "test/fixtures/font.otf",
  :glyph_indices => {:languages => ['Czech', 'Slovak'], :custom_characters => '☃û'},
  :destination => "output", :font_name => 'Metalista',
  :export_to => [:woff, :svg, :eot, :otf], :without => [:kerning])
```

Budu muset dopsat readme a dokoumat `Figures`. Už je mám i s pozicí, jenom s nima správně zatočit. Kdyby mi to nešlo, tak to budu muset sprostě nahrazovat. Stihnu to dnes během dne. Víc info zatim než bude readme najdeš v testech. Název sady 'Czech', 'Slovak' je stejnej jako v modelu.

**Comment by pepe** [comment]
Paráda! To už půjde dobře teď. Jen jedna věc co se bude muset vyřešit a to je ta výška? Umíš s ní hýbat? Zatím bych to prošel a zjistil, kde je to potřeba.

**Comment by simi** [comment]
Zkoušel jsem se dostat i do formuláře, ale nešlo mi to. Tak asi budu potřebovat novou DB + soubory. Na výšku kouknu. Ale je tam v podstatě všechno. Horší je, že to nemá dobrou dokumentaci. Takže parametry zjišťuju pokus - omyl.
